### ISSUE TITLE
SDK: capability to minify the dependencies 

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/catalogue#868]
Be sure that no duplicates dependencies are around.

**Comment by ribeiroct** [comment]
If the url is the same, we wont load it twice, as of right now. 

But for other cases this is a non-trivial problem that in my opinion should be solved manually. Since approval is manual, this should be checked on approval.

Because there's no way to correctly conciliate different dependency of external libraries into a single file, and names/paths for the same dependency may greatly vary even in the same version.

**Comment by ribeiroct** [comment]
@bastiao : We will never be able to minify dependencies into a single file, due to the architecture of the plugin system and unpredictability of each user environment of choosen plugins. Everything is loaded clientside, and minification is a serverside process.
 
We are already only loading the same file once. Can we close this as wontfix ?
